### ISSUE TITLE
Feature: Integrate code coverage for PHP

### ISSUE THREAD

**Issue by denizaygun** [luisaveiro/localhost-sonarqube#6]
In order to setup code-coverage detection there's a few steps an individual typically has to follow which this project could offer right from the start, some at least explained in docs/README.

#### Detailed Description
By default a SonarQube project is marked as failed (after a scan) when code-coverage hasn't been setup and integrated (assuming you have tests or are planning to add them). 

Therefore, instead of disabling the code coverage checks we must set them up and a few steps are involved in doing so.

The setup process may vary slightly from language to language but having a basic guide to follow for PHP specifically could give something for other languages to be based off. 

#### Additional Context
As mentioned, this will be helpful to achieve code-coverage detection in SonarQube. 

#### Possible Implementation
1. Install phpunit and Xdebug
2. Update the phpunit.xml 
3. Generate coverage report with `phpunit --coverage-clover coverage-report.xml`
4. Update the SonarQube project properties:
```
sonar.php.coverage.reportPaths=coverage-report.xml
sonar.php.tests.reportPath=tests-report.xml
```

Some other steps may also be required but this is a very quick insight and a PR will be followed up with a proper implementation.

#### Alternative Implementation
n/a
#### Your Environment
Localhost SonarQube version used: 1.0.0
Operating System and version: macOS Big Sur 11.1

**Comment by luisaveiro** [comment]
@denizaygun the primary objective of this project was to provide a developer friendly CLI tool to setup and interact with SonarQube without requiring developers to have the knowledge on how to install SonarQube and SonarScanner dependencies or how to use Docker CLI. As per the [Disclaimer section](https://github.com/luisaveiro/localhost-sonarqube#disclaimer) in the readme.

```
Please note: This readme assumes you are familiar with SonarQube and will not be covering on 
how to setup projects in SonarQube and configure sonar-project.properties files to analyse a project. 
Please visit SonarQube Documentation for additional instructions.
```

SonarQube can analyse up to **27 different languages** and in the [Guides](https://community.sonarsource.com/c/announce/guides/22) category of the [SonarSource Community forum](https://community.sonarsource.com/) you might find instructions on generating the test coverage and execution reports.


I have updated the Laravel SonarScanner template in [v0.1.2](https://github.com/luisaveiro/localhost-sonarqube/releases/tag/v0.1.2) to include test coverage & execution properties.

```
# --- test coverage & execution properties ---

# Comma-delimited list of paths to Clover XML-format coverage report files.
# Paths may be absolute or relative to project root.
#sonar.php.coverage.reportPaths=

# Path to the PHPUnit unit test execution report file. Path may be absolute or
# relative to project root.
#sonar.php.tests.reportPath=
```

I have enabled the [Wiki section](https://github.com/luisaveiro/localhost-sonarqube/wiki) in the repo to allow us to provide additional documentation on configuring SonarQube project properties. The repo does have a [Discussion section](https://github.com/luisaveiro/localhost-sonarqube/discussions) as well for developers to provide suggestions or need additional assistance.

However if developers are struggling to use SonarQube and not the CLI tool that this repo provides; I would recommend developers to visit [SonarSource Community forum](https://community.sonarsource.com/). Since they would be more successful in receiving a resolution for their issue because this repo is not affiliated with SonarSource SA and is not an official product
